### ISSUE TITLE
Market OreDict Sell Option

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#10]
Add an option to sell OreDict items
For example:
  "ingotCopper": {
    "stackObj": "thermalfoundation:material", (Thermal Exp Copper ingot)
    "amount": 128,
    "value": 10,
    "isBuy": false,
    **"oreDict": true** (Will accept all oredicted ingots, work only for _"isBuy": false_)
  }

**Comment by DevTimur** [comment]
Actually any other wayt o implement this will do.

**Comment by Calemi** [comment]
I see what you're saying here, but it might be difficult to explain to players. I might use "stackObj" as the name for both ore dictionary ("oreBlock") and regular items ("minecraft:") and the mod can just look for any ore dictionaries matching. I don't see a problem with this method as there will be no ore dicts with "modid:item" so it shouldn't interfere. Having it only work on selling makes sense as well. Thanks for this idea!
