### ISSUE TITLE
Interaction Terminal Search Tab

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#11]
I know there is already many storage managing mods (like AE2, RS, SSN)
But i think it would be cool feature if you could search for item name inside of Interaction Terminal
![image](https://user-images.githubusercontent.com/22171136/58542784-dcf57800-8206-11e9-9baf-2c9cad907d3b.png)
Somewhere here.
And it highlight inventory with this item.

Ofcourse if it's easy to make and you want to make it.

**Comment by Calemi** [comment]
Interesting! Definitely considering this.
