### ISSUE TITLE
More Interaction Interface & Filter Options

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#13]
More optionf for Interaction Interface

![image](https://user-images.githubusercontent.com/22171136/58544017-3068c580-8209-11e9-875f-ba98f8f870fc.png)

Not only Name and Icon for tab but for Inventory aswell.

**Comment by Calemi** [comment]
I like the tooltip addition, but I'm not quite sure what the other icon is for.

**Comment by DevTimur** [comment]
That is quite optional, to change icon for inventory.
But now i think changing name will suffice.

**Comment by Calemi** [comment]
Ah, I see. I'll have to add these to the Interaction Interface as well.

![7939a561aee0da91bdc46dc0c3ef0d7b](https://user-images.githubusercontent.com/11864216/58548402-3e055780-81d7-11e9-8f2e-d27eb78e14d7.png)
![ceae755dd18dc4c88d80a8d33dbf8c15](https://user-images.githubusercontent.com/11864216/58548405-3fcf1b00-81d7-11e9-9309-2a24a7c7ad9b.png)

So like this?

**Comment by DevTimur** [comment]
Um... no.
Like this
![image](https://user-images.githubusercontent.com/22171136/58552602-7b8bd400-821b-11e9-8bf9-489d2cf5ed0e.png)

**Comment by DevTimur** [comment]
wait.... um...
So you split filter and interface?
That confused me.
ok... let me think...

I think it would be more understandable if:
![image](https://user-images.githubusercontent.com/22171136/58552982-619ec100-821c-11e9-9819-04b37e2a3e29.png)

and

![image](https://user-images.githubusercontent.com/22171136/58552873-1ab0cb80-821c-11e9-9cbb-4fadc26505a6.png)

**Comment by Calemi** [comment]
I see. I just had to throw out what I interpreted with images to get on the same page. The filter and interfere were always split btw.

First, I think I will rename the filter to something more understandable like "II Tab". Then proceed to implement what was said.

Also these changes will take a while to implement and get currently, so I'll get to it when I do.
