### ISSUE TITLE
[BUG] Interaction Interface missbehave

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#14]
Re-produce
1) Have Interaction Interface with Tab filter (Icon, name, all the things)
2) Open Interface and click upgrade icon to delete filter
3) Open Interface 2 (TWO) times, Filter will pop back up. (Including in terminal)

https://i.gyazo.com/8ac120505a4fd8dcaa01153c8fc65290.gif

**Comment by Calemi** [comment]
Ah, this old bug still found its way through. Thanks for the report!
