### ISSUE TITLE
[BUG] Network Cables does not STACK

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#15]
Yeah... this issue is back in 1.0.7 version
Unstackable cables

**Comment by Calemi** [comment]
Come on, really?! 

![d1f2d0b217804e4402bc61e63006759b](https://user-images.githubusercontent.com/11864216/58548758-f6cb9680-81d7-11e9-90f2-e1c181d46a65.png)

I don't even know why this is even here lol! I'll push a fix in a bit.
