### ISSUE TITLE
Interaction Interface Max Distance on Chests

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#16]
Depending on distance to chests you see or doesn't see them in Terminal

https://i.gyazo.com/26ab43231f4a73b8499a4de68c8404d0.gif

**Comment by DevTimur** [comment]
If you gona say that OK then why Crafting Table and ME Chests work with ANY distance?

**Comment by Calemi** [comment]
That is how Minecraft handles their vanilla containers. The crafting table also as a max distance. It's just longer than chests. I can't really do anything about it sadly. There isn't any way of overriding it.
