### ISSUE TITLE
"Suck" Should Suck by Stacks

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#18]
Increase items sucking speed to a stack size instead of one item on a time.
I'm talking about Wallet and Builder's kit

BTW, you got typo in "Builders' kit".

**Comment by Calemi** [comment]
I could change this for the Builder's Kit easily but the wallet is another problem entirely. Going by stacks, I would have to calculate how much the total value of that stack and see if it can fit into your wallet's capacity before sucking it. It's possible but complicated.
