### ISSUE TITLE
Baubles are optional

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#2]
Make Baubles optional mod instead of required.
Is player doesn't have Baubles, just disable this section of code.

**Comment by Calemi** [comment]
I've already tried very hard to get Baubles to be optional. Maybe I'm misunderstanding something, but baubles use an interface to register it, and there isn't a way to remove that interface depending on if the mod is installed. And yes, I've tested the mod without Baubles installed, and it crashes.

If you know of a specific way of doing this, please let me know. I would love to get Baubles to be optional

**Comment by DevTimur** [comment]
I am not a coder. All I can suggest is look how it had been done by someone else, and do the same.
For example https://github.com/TheUnderTaker11/Better-Magnets/tree/1.12.2/src/main
Baubles are optional in that mod

**Comment by Calemi** [comment]
I have fixed this instantly! Thank you so much for this! Fix will be in v1.0.4.
