### ISSUE TITLE
Blueprints Allow Any Block to be Placed

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#21]
Floating CactoCUBE
![image](https://user-images.githubusercontent.com/22171136/58558190-d677f800-8228-11e9-91cb-521e0b64ae54.png)

Triplechest
https://i.gyazo.com/fec182312d5f34b24c0e8dbc8a37eccb.gif

**Comment by DevTimur** [comment]
And yes, i used blueprint block to place them.

**Comment by Calemi** [comment]
Noted lol.
