### ISSUE TITLE
Scaffold Tweaks

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#22]
List of Scaffold tweaks:
1) Scaffolds should work as ladders aswell. Or even better, how they work in 1.14 (Not solid, and you can travel inside, but that's ideal situation)
2) Left-clicking should extend scaffold UP, and Shift+left-click should place in direction your BODY is facing (second part is implemented already, but work with simple L-click)
3) Mining level set to 0 (so you can break with open arm)
4) Breaking speed make similar to "Leaves", so you can break it faster

-=<I like how you get all connected blocks back if Shift-break, keep it>=-

**Comment by Calemi** [comment]
I've tried to get them to act like ladder but sadly it's not in my skillset. When updating this mod to 1.12 it broke the ladder functionality and I can't get it back ever since. The break speed and harvest levels make sense though so I'll look into those.
