### ISSUE TITLE
New Pencil Function (Copy built structures into templates)

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#23]
Shift+left-click on a block with a Pencil should spawn "Building Unit Template" of all similar connected blocks. (Not work with Blueprint blocks, for a reason)

Example:
You see statue made of diamond and gold blocks you would like to copy, you take pencil, select color, Shift+left-click diamond block and get template of all diamond blocks that touch each other. With color you selected.
You change color and Shift+left-click gold block, get template with other color blocks.
Then you can use Building Unit to spawn different parts of statue, and then "build" it using blocks you like.
![image](https://user-images.githubusercontent.com/22171136/58560358-a4b56000-822d-11e9-8fd9-51c3b1a12fcf.png)

**Comment by DevTimur** [comment]
And another Pencil function:
Shift+right-clicking on Bluepring block will **adopt it's color**.

**Comment by DevTimur** [comment]
I got change of idea.
Pencil:
Left-click will add overlay to a blocks (some form of highlight), with color, of course.
Shift+Left-click will add overlay to all similar and touching blocks.
Eraser:
will remove highlight

Then you can use Building Unit to make a Template of all highlighted blocks and blueprint blocks.

**Comment by Calemi** [comment]
I like this idea but couldn't we just:

- Add button that toggles between reading Blueprints and Blocks
- When in block mode, the Unit will read anything in the area.
- Blocks will be converted into Blueprints (Example: the first block it sees is black, then the next different block is gray etc) Allowing 16 different blocks to read in one single action. 

This allows players to copy their creations that are already built. Also the Markers can be used to determine it's size so players can control what they want read.
