### ISSUE TITLE
Building Unit Should Copy Templates When Placed Into Inventory

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#24]
If you insert Template in Building unit, and then just break it, you will lose all inserted Templates.

I would like to REQUEST function when you Right-click Building Unit with template, it just COPY template in (Or ghost item, if you like, how it done in Interaction Interface with Filter), that way you can re-use same template in many building units.

It would be cool if it anounce in chat about that function. Like "Template copied in Building Unit"

**Comment by DevTimur** [comment]
If you use Wrench, it save inventory.
But if you just punch it, no inventory saved.

**Comment by Calemi** [comment]
Well yes, but that in creative so it would never happen in survival. I mean, I could add a drop function for creative mode if it is really necessary.

**Comment by DevTimur** [comment]
Lol no, I break builder with empty handed in survival

**Comment by Calemi** [comment]
Huh, well that's not right lol
