### ISSUE TITLE
Market Auto-sell/buy not working if placed BEFORE Bank

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#26]
If you place Market, setup auto-sell/buy funcion, and THEN place Bank in network, buy/sell operation will not go.

**Comment by DevTimur** [comment]
WAIT....
There is something finiky with Bank block...
When i place Market on top of Bank block, automation does not work...

**Comment by Calemi** [comment]
Okay that should be a simple fix; just gotta check if it's not a bank. Is that the only problem, or is the placing before bank thing a problem too?

**Comment by DevTimur** [comment]
Sorry, wasn't sure how does it work in first place...
So, if you got inventory with items you want to sell on top or bottom side of market it will automatically pull items, right? 
If so then no, placing order is not a problem. I just was confused how it works.
But there is something annoying. You can't pump items out using pipes.
Also, bank is considered an inventory and if you place market on top or bottom of bank then market try to scan it for items to sell, and automation just breaks. I guess same issue will happen if you got multiple inventories touching market?

**Comment by Calemi** [comment]
Okay that clears things up but couldn't you just pump items in and out of chests that are adjacent to the Market? That was the whole idea when I was developing it.

**Comment by DevTimur** [comment]
Market itself is slow.
After all other mods I would expect to boost  speed with better pumping system, but it limited by market itself.
As if I could increase item buying speed, with upgrade for example.

**Comment by DevTimur** [comment]
I like how you implemented progress bar in quarry mining unit. It is understandable that one process takes X time, and can be boosted using upgrades. If you don't want to make batch sales, maybe you can add upgrade support?

**Comment by Calemi** [comment]
Ah okay I understand. I'll implement the batch purchases and increase the speed a bit. Also I'll make the Market only read from the top and change the texture to indicate to players. And remove the bank bug of course. Sound good?

**Comment by DevTimur** [comment]
Perfect
