### ISSUE TITLE
Batch Purchases & Selling Options

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#28]
> I'm not sure why you limited insertion/extraction to only hoppers, but is it possible to add Pipes/Itemducts/Inserters/Conveyors support?

Lol, silly me. That not about hoppers, that about any inventory on top or bottom of market

So, can you add buttons for BATCH purchases at one operation cycle?
![image](https://user-images.githubusercontent.com/22171136/58619431-9880df80-82cd-11e9-838b-4ae451ede1c6.png)
And probably it should work with Auto-buying too.

**Comment by Calemi** [comment]
Yeah this was an idea that I was going to implement in the first version, but then I got to focused on getting just the Market itself working.
