### ISSUE TITLE
Upgrade tweak and dynamic price

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#29]
1 You made so only 5 upgrades allowed per machine. Can you increase it, or make configurable?

2 upgrading machine does not have downsides. Consider adding additional cost per operation for upgraded machine. For example +5% to price per upgrade. Configurable?

**Comment by Calemi** [comment]
I think I can manage adding a stacksize config option. The downside could work but percentages wouldn't make much sense with whole numbers (5% of 1 wouldn't change anything. Even 50%). If another downside exists, it might be better.

**Comment by DevTimur** [comment]
You can make so if with cost of 1 you add 49% or less, it stay 1, but if 50% and more it increase by 1. Basically round up number to closest whole number.
