### ISSUE TITLE
Location Link Book Fatal Error

### ISSUE THREAD

**Issue by Darkfiend009** [Calemi/CalemiUtils#3]
**Describe the bug**
The Location Link Book disconnects client's when used on my server with a fatal error.

**To Reproduce**
Happens every time we attempt to use the book.

**Screenshots**
Here is the server log with the fatal error info:
https://pastebin.com/dvgpp0b7

**Singleplayer or Multiplayer?**
Multiplayer

**Other Mods Installed**
Mod list:
https://pastebin.com/2W1YAmXy

**Comment by Calemi** [comment]
Seems like I didn't test this one thoroughly, whoops :P. This should be a simple fix and it'll make it in v1.0.5. Thanks for the report!

**Comment by Darkfiend009** [comment]
No problem! Happy to help wherever i can.

**Comment by Calemi** [comment]
Version 1.0.5 is out, and this one is fixed! I'm still surprised this one slipped through.
