### ISSUE TITLE
Sledgehammers crash when used on Dynamic Trees roots

### ISSUE THREAD

**Issue by slowiu06** [Calemi/CalemiUtils#32]
Sledgehammers crashes game when used on Dynamic Trees larger trees roots (eg. Thaumcraft trees)
https://pastebin.com/xyEAVUut

Is there a way to reduce sledgehammers damage/aspd? They are a bit OP right now, which makes other weapons useless. Incrasing RBM cooldown/cast will be good too.

**Comment by Calemi** [comment]
Yikes, noted. And lowering the damage sounds good too.
