### ISSUE TITLE
Wrong output slot in Miner

### ISSUE THREAD

**Issue by DevTimur** [Calemi/CalemiUtils#5]
https://i.gyazo.com/333356a18ed17bfed5919b10368dfd02.gif

**Comment by DevTimur** [comment]
On second thought... Mining unit is BROKEN AS HELL
Every ore piece get in upgrade stols increase mining speed
What's wrong with this copper ore spam? Why 2 ores?
https://i.gyazo.com/edf03e3b8f48fd8089c1aa8fd8f229ad.gif

**Comment by Calemi** [comment]
Whaaaaaat? Looking into this now.

**Comment by DevTimur** [comment]
same deal with Quarry btw
It fill upgrade slots
and
fill inventory with "2 stone blocks"

**Comment by DevTimur** [comment]
https://i.gyazo.com/b55c24982e88ad13c70626a9938eb0f6.gif

**Comment by Calemi** [comment]
Okay, I just reproduced it. It should be a simple fix.

**Comment by Calemi** [comment]
Alright, just fixed those bugs. Now to move on to the other one.
