### ISSUE TITLE
Server crash with latest version 1.0.6

### ISSUE THREAD

**Issue by Darkfiend009** [Calemi/CalemiUtils#9]
When trying to launch a server with the latest update to the mod (1.0.6), it crashes with a fatal error.

Here is the crash log: https://pastebin.com/wwJ1hN6i

Minecraft: 1.12.2
Forge: 2836

**Comment by Calemi** [comment]
Well that's not good. I'll fix this later tonight. It sucks that such a major bug made it through.

**Comment by Darkfiend009** [comment]
It's all part of coding and modding! Don't be too hard on yourself. You've made an awesome mod here!

**Comment by Calemi** [comment]
Yeah you're right. I'll get this version all fixed up though when I get home. I'm gonna go and test the whole mod again, and on Multiplayer as well to get everything straight. Thanks for your help! It's always appreciated.
